Ravelin: SHAREDMATRIXN Class Reference
SHAREDMATRIXN Class Reference
A generic, possibly non-square matrix using shared data.
#include <SharedMatrixN.h>
Public Member Functions
SHAREDMATRIXN (const SHAREDMATRIXN &source)
Copy constructor.
SHAREDMATRIXN (unsigned rows, unsigned cols, unsigned leading_dim, unsigned start, SharedResizable< REAL > data)
Constructs the matrix using the given arguments.
void reset_from (const SHAREDMATRIXN &source)
Resets this from another shared matrix.
SHAREDMATRIXN & set_identity ()
Sets this matrix to the identity matrix.
bool is_symmetric (REAL tolerance=(REAL)-1.0) const
Checks whether the given matrix is symmetric to the specified tolerance.
REAL norm_inf () const
SHAREDMATRIXN & zero_upper_triangle ()
Zeros the upper triangle of the matrix.
SHAREDMATRIXN & zero_lower_triangle ()
Zeros the lower triangle of the matrix.
unsigned rows () const
unsigned columns () const
unsigned leading_dim () const
SHAREDMATRIXN & resize (unsigned rows, unsigned columns, bool preserve=false)
Resizes this matrix, optionally preserving its existing elements.
SHAREDMATRIXN & negate ()
Negates this matrix in place.
SHAREDMATRIXN & set_zero ()
Sets the matrix to the zero matrix.
SHAREDMATRIXN & operator/= (REAL scalar)
Divides this matrix by a scalar in place.
SHAREDMATRIXN & operator*= (REAL scalar)
Multiplies this matrix by another in place.
SHAREDMATRIXN & operator= (const MATRIX3 &m)
Sets a matrix from a MATRIX3.
SHAREDMATRIXN & operator= (const MATRIXN &source)
Sets a matrix from a MATRIXN.
SHAREDMATRIXN & operator= (const SHAREDMATRIXN &source)
Sets a matrix from a MATRIXN.
SHAREDMATRIXN & operator= (const CONST_SHAREDMATRIXN &source)
Sets a matrix from a MATRIXN.
REAL & operator() (unsigned i, unsigned j)
Accesses the given element.
const REAL & operator() (unsigned i, unsigned j) const
Accesses the given element.
REAL * data ()
const REAL * data () const
void reset ()
Resets the shared matrix.
CONST_SHAREDVECTORN row (unsigned i) const
Gets the specified sub matrix.
CONST_SHAREDVECTORN column (unsigned i) const
Gets a shared vector for a column.
CONST_SHAREDMATRIXN block (unsigned row_start, unsigned row_end, unsigned col_start, unsigned col_end) const
Gets a block as a constant shared matrix.
SHAREDVECTORN row (unsigned i)
Gets a shared vector for a row.
SHAREDVECTORN column (unsigned i)
Gets a shared vector for a column.
SHAREDMATRIXN block (unsigned row_start, unsigned row_end, unsigned col_start, unsigned col_end)
Gets a block as a shared matrix.
template<class V >
XMATRIXN & set (const V &v, Transposition trans)
Sets a matrix from a vector.
template<class M >
XMATRIXN & operator+= (const M &m)
Adds m to *this in place.
template<class M >
XMATRIXN & operator-= (const M &m)
Subtracts m from *this in place.
XMATRIXN & set_zero (unsigned m, unsigned n)
Sets this to a m x n sized zero matrix.
CONST_COLUMN_ITERATOR block_column_iterator_begin (unsigned row_start, unsigned row_end, unsigned col_start, unsigned col_end) const
This file consists of general routines for constant matrices.
CONST_COLUMN_ITERATOR block_column_iterator_end (unsigned row_start, unsigned row_end, unsigned col_start, unsigned col_end) const
Gets a column iterator to a block.
CONST_ROW_ITERATOR block_row_iterator_begin (unsigned row_start, unsigned row_end, unsigned col_start, unsigned col_end) const
Gets a row iterator to a block.
CONST_ROW_ITERATOR block_row_iterator_end (unsigned row_start, unsigned row_end, unsigned col_start, unsigned col_end) const
Gets a row iterator to a block.
template<class V >
V & get_row (unsigned row, V &v) const
template<class V >
V & get_column (unsigned column, V &v) const
template<class T , class U >
U & transpose_mult_transpose (const T &x, U &y, REAL alpha=(REAL) 1.0, REAL beta=(REAL) 0.0) const
Does the operation y = beta*y + alpha*this'*x'.
template<class T , class U >
U & mult_transpose (const T &x, U &y, REAL alpha=(REAL) 1.0, REAL beta=(REAL) 0.0) const
Does the operation y = beta*y + alpha*this*x'.
template<class T , class U >
U & transpose_mult (const T &x, U &y, REAL alpha=(REAL) 1.0, REAL beta=(REAL) 0.0) const
Does the operation y = beta*y + alpha*this'*x.
template<class T , class U >
U & mult (const T &x, U &y, REAL alpha=(REAL) 1.0, REAL beta=(REAL) 0.0) const
Does the operation y = beta*y + alpha*this*x.
template<class M >
M & get_sub_mat (unsigned row_start, unsigned row_end, unsigned col_start, unsigned col_end, M &m, Transposition trans=eNoTranspose) const
Gets the specified sub matrix.
template<class ForwardIterator , class M >
M & select_columns (ForwardIterator col_start, ForwardIterator col_end, M &m) const
Gets a submatrix of columns (not necessarily a block)
template<class M >
M & select_columns (std::vector< bool > &col_select, M &m) const
Gets a submatrix of columns (not necessarily a block)
template<class ForwardIterator , class M >
M & select_rows (ForwardIterator row_start, ForwardIterator row_end, M &m) const
Gets a submatrix of rows (not necessarily a block)
template<class M >
M & select_rows (std::vector< bool > &row_select, M &m) const
Gets a submatrix of rows (not necessarily a block)
template<class ForwardIterator1 , class ForwardIterator2 , class X >
X & select (ForwardIterator1 row_start, ForwardIterator1 row_end, ForwardIterator2 col_start, ForwardIterator2 col_end, X &m) const
Gets a submatrix (not necessarily a block)
template<class X >
X & select (const std::vector< bool > &rows, const std::vector< bool > &cols, X &m) const
Gets a submatrix (not necessarily a block)
template<class M >
M & select_square (const std::vector< bool > &indices, M &result) const
Gets a square submatrix (not necessarily a block)
template<class ForwardIterator , class M >
M & select_square (ForwardIterator start, ForwardIterator end, M &m) const
CONST_COLUMN_ITERATOR column_iterator_begin () const
Get an iterator to the beginning.
CONST_COLUMN_ITERATOR column_iterator_end () const
Get an iterator to the end.
CONST_ROW_ITERATOR row_iterator_begin () const
Get an iterator to the beginning.
CONST_ROW_ITERATOR row_iterator_end () const
Get an iterator to the end.
COLUMN_ITERATOR block_column_iterator_begin (unsigned row_start, unsigned row_end, unsigned col_start, unsigned col_end)
Gets a column iterator to a block.
COLUMN_ITERATOR block_column_iterator_end (unsigned row_start, unsigned row_end, unsigned col_start, unsigned col_end)
Gets a column iterator to a block.
ROW_ITERATOR block_row_iterator_begin (unsigned row_start, unsigned row_end, unsigned col_start, unsigned col_end)
Gets a row iterator to a block.
ROW_ITERATOR block_row_iterator_end (unsigned row_start, unsigned row_end, unsigned col_start, unsigned col_end)
Gets a row iterator to a block.
template<class V >
MATRIXX & set_row (unsigned row, const V &v)
template<class V >
MATRIXX & set_column (unsigned column, const V &v)
template<class M >
MATRIXX & set_sub_mat (unsigned row_start, unsigned col_start, const M &m, Transposition trans=eNoTranspose)
Sets the specified sub matrix.
ROW_ITERATOR row_iterator_begin ()
Get an iterator to the beginning (iterates column by column)
ROW_ITERATOR row_iterator_end ()
Get an iterator to the end.
COLUMN_ITERATOR column_iterator_begin ()
Get an iterator to the beginning (iterates column by column)
COLUMN_ITERATOR column_iterator_end ()
Get an iterator to the end.
Static Public Member Functions
template<class M >
static M & transpose (const XMATRIXN &m, M &result)
Determines the transpose of a matrix and stores the result in a given matrix.
template<class V , class W >
static W & diag_mult (const V &d, const XMATRIXN &m, W &result)
Multiplies the diagonal matrix formed from d by the matrix m.
template<class V , class W >
static W & diag_mult_transpose (const V &d, const XMATRIXN &m, W &result)
Multiplies the diagonal matrix formed from d by the matrix transpose(m)
template<class V , class U , class W >
static W & diag_mult (const V &d, const U &v, W &result)
Determines the transpose of a matrix and stores the result in a given matrix.
Protected Attributes
SharedResizable< REAL > _data
unsigned _rows
unsigned _start
unsigned _columns
unsigned _ld
Friends
class MATRIXN
class CONST_SHAREDMATRIXN
Detailed Description
A generic, possibly non-square matrix using shared data.
The underlying data is stored in column-major format (e.g., the element at row 1, column 0 is the second element in the flat array).
Member Function Documentation
CONST_COLUMN_ITERATOR SHAREDMATRIXN::block_column_iterator_begin (unsigned row_start, unsigned row_end, unsigned col_start, unsigned col_end) const inline
This file consists of general routines for constant matrices.
Gets a column iterator to a block
template<class V , class U , class W > static W& SHAREDMATRIXN::diag_mult (const V & d, const U & v, W & result) inline static
Determines the transpose of a matrix and stores the result in a given matrix.
Multiplies the diagonal matrix formed from d by the vector v
template<class M > M& SHAREDMATRIXN::get_sub_mat (unsigned row_start, unsigned row_end, unsigned col_start, unsigned col_end, M & m, Transposition trans = eNoTranspose) const inline
Gets the specified sub matrix.
Parameters
row_start the row to start (inclusive)
row_end the row to end (exclusive)
col_start the column to start (inclusive)
col_end the column to end (exclusive)
transpose determines whether to store the transpose of the submatrix into m
Returns
a (row_end - row_start) x (col_end - col_start) sized matrix
SHAREDMATRIXN & SHAREDMATRIXN::resize (unsigned rows, unsigned columns, bool preserve = false)
Resizes this matrix, optionally preserving its existing elements.
Note
this method keeps from reallocating memory unless absolutely necessary (i.e., if the matrix grows or preserve=true, then memory will need to be reallocated.
Referenced by CRB_ALGORITHM::calc_generalized_inertia(), and operator=().
CONST_SHAREDVECTORN SHAREDMATRIXN::row (unsigned i) const inline
Gets the specified sub matrix.
Parameters
row_start the row to start (inclusive)
row_end the row to end (exclusive)
col_start the column to start (inclusive)
col_end the column to end (exclusive)
transpose determines whether to store the transpose of the submatrix into m
Returns
a (row_end - row_start) x (col_end - col_start) sized matrixGets a constant shared vector for a row
template<class ForwardIterator1 , class ForwardIterator2 , class X > X& SHAREDMATRIXN::select (ForwardIterator1 row_start, ForwardIterator1 row_end, ForwardIterator2 col_start, ForwardIterator2 col_end, X & m) const inline
Gets a submatrix (not necessarily a block)
Parameters
row_start an iterator pointing to the beginning of a container of row indices (container need not be sorted)
row_end an iterator pointing to the end of a container of row indices (container need not be sorted)
col_start an iterator pointing to the beginning of a container of column indices (container need not be sorted)
col_end an iterator pointing to the end of a container of column indices (container need not be sorted)
M contains the submatrix on return
template<class ForwardIterator , class M > M& SHAREDMATRIXN::select_columns (ForwardIterator col_start, ForwardIterator col_end, M & m) const inline
Gets a submatrix of columns (not necessarily a block)
Parameters
col_start an iterator pointing to the beginning of a container of column indices (container need not be sorted)
col_end an iterator pointing to the end of a container of column indices (container need not be sorted)
M contains the submatrix on return
template<class M > M& SHAREDMATRIXN::select_columns (std::vector< bool > & col_select, M & m) const inline
Gets a submatrix of columns (not necessarily a block)
Parameters
col_select a vector of bools; if the entry is true in the vector, the column is selected
M contains the submatrix on return
template<class ForwardIterator , class M > M& SHAREDMATRIXN::select_rows (ForwardIterator row_start, ForwardIterator row_end, M & m) const inline
Gets a submatrix of rows (not necessarily a block)
Parameters
row_start an iterator pointing to the beginning of a container of row indices (container need not be sorted)
row_end an iterator pointing to the end of a container of row indices (container need not be sorted)
M contains the submatrix on return
template<class M > M& SHAREDMATRIXN::select_rows (std::vector< bool > & row_select, M & m) const inline
Gets a submatrix of rows (not necessarily a block)
Parameters
row_select a vector of bools; if the entry is true in the vector, the row is selected
M contains the submatrix on return
template<class ForwardIterator , class M > M& SHAREDMATRIXN::select_square (ForwardIterator start, ForwardIterator end, M & m) const inline
Parameters
start an iterator pointing to the beginning of a container of row/column indices (container need not be sorted)
end an iterator pointing to the end of a container of row/column indices (container need not be sorted)
M contains the submatrix on return
template<class M > MATRIXX& SHAREDMATRIXN::set_sub_mat (unsigned row_start, unsigned col_start, const M & m, Transposition trans = eNoTranspose) inline
Sets the specified sub matrix.
Parameters
row_start the row to start (inclusive)
col_start the column to start (inclusive)
m the source matrix
transpose determines whether the m is to be transposed
Note
fails assertion if m is too large to insert into this
Referenced by CRB_ALGORITHM::calc_generalized_inertia(), and operator=().
The documentation for this class was generated from the following files:
/home/drum/Ravelin.new/include/Ravelin/SharedMatrixN.h
/home/drum/Ravelin.new/src/SharedMatrixN.cpp